#!/bin/bash
set -euo pipefail

# Setup script for secret keys on the cluster
# Stores secrets in VAST for persistence across nodes

VAST_PREFIX="${VAST_PREFIX:-/workspace-vast/$(whoami)}"
SECRETS_FILE="$VAST_PREFIX/.secrets.sh"

echo "Secret keys setup"
echo "================="
echo "Secrets will be stored in: $SECRETS_FILE"
echo ""

# Function to prompt for a secret (with hidden input)
prompt_secret() {
    local var_name="$1"
    local current_value="${2:-}"

    if [[ -n "$current_value" ]]; then
        echo "Current value exists for $var_name"
        read -p "  Overwrite? [y/N]: " overwrite
        if [[ ! "$overwrite" =~ ^[Yy]$ ]]; then
            echo "  Keeping existing value"
            return 1
        fi
    fi

    read -p "  Enter value for $var_name (or leave empty to skip): " value

    if [[ -n "$value" ]]; then
        echo "$value"
        return 0
    fi
    return 1
}

# Load existing secrets if present
declare -A existing_secrets
if [[ -f "$SECRETS_FILE" ]]; then
    echo "Found existing secrets file"
    while IFS= read -r line; do
        if [[ "$line" =~ ^export\ ([A-Za-z_][A-Za-z0-9_]*)= ]]; then
            var_name="${BASH_REMATCH[1]}"
            existing_secrets["$var_name"]=1
        fi
    done < "$SECRETS_FILE"
    echo ""
fi

# Start building new secrets file
new_secrets=""

# Predefined secrets to prompt for
PREDEFINED_SECRETS=(
    "ANTHROPIC_API_KEY_BATCH"
    "ANTHROPIC_API_KEY_LOW"
    "ANTHROPIC_API_KEY_HIGH"
)

echo "Prompting for predefined secrets..."
for secret_name in "${PREDEFINED_SECRETS[@]}"; do
    current="${existing_secrets[$secret_name]:-}"
    if value=$(prompt_secret "$secret_name" "$current"); then
        new_secrets+="export $secret_name=\"$value\"\n"
        unset "existing_secrets[$secret_name]"
    elif [[ -n "$current" ]]; then
        # Keep existing value by re-reading from file
        existing_line=$(grep "^export $secret_name=" "$SECRETS_FILE" 2>/dev/null || true)
        if [[ -n "$existing_line" ]]; then
            new_secrets+="$existing_line\n"
            unset "existing_secrets[$secret_name]"
        fi
    fi
done

echo ""
echo "Add custom secrets (enter empty name to finish):"
while true; do
    read -p "  Secret name (e.g., MY_API_KEY): " custom_name
    [[ -z "$custom_name" ]] && break

    # Validate variable name
    if [[ ! "$custom_name" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]]; then
        echo "  Invalid variable name. Use only letters, numbers, and underscores."
        continue
    fi

    current="${existing_secrets[$custom_name]:-}"
    if value=$(prompt_secret "$custom_name" "$current"); then
        new_secrets+="export $custom_name=\"$value\"\n"
        unset "existing_secrets[$custom_name]"
    elif [[ -n "$current" ]]; then
        existing_line=$(grep "^export $custom_name=" "$SECRETS_FILE" 2>/dev/null || true)
        if [[ -n "$existing_line" ]]; then
            new_secrets+="$existing_line\n"
            unset "existing_secrets[$custom_name]"
        fi
    fi
done

# Preserve any remaining existing secrets that weren't touched
for remaining_name in "${!existing_secrets[@]}"; do
    existing_line=$(grep "^export $remaining_name=" "$SECRETS_FILE" 2>/dev/null || true)
    if [[ -n "$existing_line" ]]; then
        new_secrets+="$existing_line\n"
    fi
done

# Write secrets file
echo -e "# Secret keys - DO NOT COMMIT\n# Generated by setup_secrets.sh\n\n$new_secrets" > "$SECRETS_FILE"
chmod 600 "$SECRETS_FILE"

echo ""
echo "Secrets saved to $SECRETS_FILE (permissions: 600)"
echo "These will be sourced automatically by .cluster_env.sh"
